### PR TITLE
Add outer container id into pullimage request

### PR DESCRIPTION
**Pull request by stevenhorsman**
Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Review by davidhay1969 — APPROVED** [review]
LGTM - having said that, if I'm being extremely pedantic, should we make it clear to what `ID` refers, given that we have a `ContainerID` and `container_id` in different places ?

In other words, should we indicate to what the ID relates e.g. sandbox, container, PullImage process etc. ?

I assume that the protobuf variable naming convention is slightly different to Go, so using underscores rather than CamelCase is OK ...

**Comment by stevenhorsman** [comment]
Yes, 

> LGTM - having said that, if I'm being extremely pedantic, should we make it clear to what `ID` refers, given that we have a `ContainerID` and `container_id` in different places ?
> 
> In other words, should we indicate to what the ID relates e.g. sandbox, container, PullImage process etc. ?

I was trying to line up with the (seeming) containerd convention of id for the container id the command runs against and container_id from the kata agent protos, but I agree that it's not particularly clear. Do you think using `new_container_id` would be helpful?

> I assume that the protobuf variable naming convention is slightly different to Go, so using underscores rather than CamelCase is OK ...

Yes protobuf uses snake case over camelCase

**Comment by davidhay1969** [comment]
Yeah, `new_container_id` may help, especially to enable folks less familiar with ImagePull etc. 🙇‍♀️

**Review by davidhay1969 — APPROVED** [review]
LGTM 🙇‍♂️

**Pull request merged**
